workflows:
  build_from_zip:
    name: Build from ZIP
    max_build_duration: 15
    environment:
      flutter: stable
    scripts:
      - echo "Unzipping project..."
      - unzip FocusFlowFlatApp.zip
      - cd FocusFlowFlatApp
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - FocusFlowFlatApp/build/app/outputs/flutter-apk/app-debug.apk
